<?php

namespace AppBundle\Repository;

/**
 * ioc_countriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ioc_countriesRepository extends \Doctrine\ORM\EntityRepository
{
}
