<?php

namespace AppBundle\Repository;

/**
 * loc_regionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class loc_regionsRepository extends \Doctrine\ORM\EntityRepository
{
}
