<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getAllOrderedBy($order, $direction, $settings)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.isActive = 1')
            ->orderBy('a.' . $order, $direction)
        ;

        return $settings['paginator']->paginate($qb->getQuery(), $settings['page'], $settings['perPage']);
    }

    public function getOnHomepage()
    {
        return $this->createQueryBuilder('a')
            ->where('a.isOnHomepage = 1')
            ->andWhere('a.isActive = 1')
            ->orderBy('a.date', 'DESC')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult()
        ;
    }



}
